import React from "react";
import { Button, Card } from "react-bootstrap";
import Header from "./Header";

export default function Home() {
  return (
    <div>
      <Header />
      <div className="container">
        <div className="content">
          <h1>Your online wardrobe</h1>
          <div>
            <p
              className="content1"
              style={{
                textAlign: "left",
                fontSize: "20px"
              }}
            >
              We employ both 3D models and 2D images <br />
              to give an immersive try-on experience,
              <br /> as well as, provide best fit recommendations
              <br /> using data generated by our try-on features.
            </p>
            <div className="d-flex">
              <div>
                <Button
                  style={{
                    background:
                      "linear-gradient(90deg, #FF0C0C -9.67%, #004171 105.67%)"
                  }}
                >
                  Download
                </Button>
              </div>
              <div>
                <Button className="button bg-transparent">Learn More</Button>
              </div>
            </div>
          </div>
        </div>
        <div className="rectangle"></div>
      </div>
      <div>
        <div>
          <h1
            style={{ marginTop: "300px", fontWeight: "600", fontSize: "60px" }}
          >
            Why Tvish is Better?
          </h1>
        </div>
      </div>
      <div className="container1">
        <div className="content1">
          <Card classname="card">
            <h1 className="card2">01</h1>
            <h1 className="card1">Your online wardrobe</h1>
            <p
              style={{ color: "grey", textAlign: "left", paddingLeft: "20px" }}
            >
              We Enable SmartPhone Based Try On
            </p>
          </Card>
          <Card className="mt-5">
            <h1 className="card2">02</h1>
            <h1 className="card1">Your online wardrobe</h1>
            <p
              style={{ color: "grey", textAlign: "left", paddingLeft: "20px" }}
            >
              We Enable SmartPhone Based Try On
            </p>
          </Card>
          <Card className="mt-5">
            <h1 className="card2">03</h1>
            <h1 className="card1">Your online wardrobe</h1>
            <p
              style={{ color: "grey", textAlign: "left", paddingLeft: "20px" }}
            >
              We Enable SmartPhone Based Try On
            </p>
          </Card>
          <Card className="mt-5">
            <h1 className="card2">04</h1>
            <h1 className="card1">Your online wardrobe</h1>
            <p
              style={{ color: "grey", textAlign: "left", paddingLeft: "20px" }}
            >
              We Enable SmartPhone Based Try On
            </p>
          </Card>
        </div>
        <div
          style={{
            marginLeft: "200px",
            marginTop: "400px"
          }}
        >
          <img src="https://cdn.pixabay.com/photo/2021/08/09/00/00/bellflower-6532224__340.jpg" />
        </div>
      </div>
      <div>
        <div>
          <h1
            style={{ marginTop: "300px", fontWeight: "600", fontSize: "60px" }}
          >
            All You Need To Know
          </h1>
        </div>
        <div className="container1">
          <div className="content1">
            <Card classname="card">
              <h1 className="card2">01</h1>
              <h1 className="card1">Your online wardrobe</h1>
              <p
                style={{
                  color: "grey",
                  textAlign: "left",
                  paddingLeft: "20px"
                }}
              >
                We Enable SmartPhone Based Try On
              </p>
            </Card>
          </div>
          <div
            style={{
              marginLeft: "200px",
              marginTop: "100px"
            }}
          >
            <img src="https://cdn.pixabay.com/photo/2021/08/09/00/00/bellflower-6532224__340.jpg" />
          </div>
        </div>
        <div>
          <div>
            <h1
              style={{
                marginTop: "300px",
                fontWeight: "600",
                fontSize: "60px"
              }}
            >
              What They Got To Talk About Us
            </h1>
          </div>
          <div style={{ display: "flex" }}>
            <div className="rectangle2"></div>
            <div className="rectangle3"></div>
            <div className="rectangle4"></div>
            <div className="rectangle5"></div>
            <div className="rectangle6"></div>
          </div>
        </div>
      </div>
      <div>
        <div style={{ marginTop: "700px", display: "flex" }}>
          <div>
            <h1
              style={{
                marginTop: "100px",
                fontWeight: "200",
                paddingLeft: "100px",
                fontSize: "60px"
              }}
            >
              Make Contact
            </h1>
            <div style={{ paddingLeft: "100px" }}>
              <p>Fill Out the form and we will get in touch with you</p>
            </div>
          </div>
        </div>
        <div className="contact">
          <form>
            <input placeholder="Name*" />
            <br />
            <div className="mb-2" />
            <input placeholder="Email*" />
            <br />
            <div className="mb-2" />
            <input placeholder="Phone*" />
            <br />
            <div className="mb-2" />
            <input placeholder="Company*" />
            <br />
            <div className="mb-2" />
            <input placeholder="Job Title*" />
            <br />
            <div className="mb-2" />
            <label style={{ textAlign: "left" }}>Message*</label>
            <br />
            <textarea className="mb-5" />
          </form>
        </div>
      </div>
    </div>
  );
}
